//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace storelaptop.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class khachhang
    {
        [DisplayName("Mã Khách Hàng")]
        public int makhachhang { get; set; }
        [DisplayName("Tên Khách Hàng")]
        [Required(ErrorMessage = "Bạn phải nhập tên khách hàng")]
        public string tenkhachhang { get; set; }
        [DisplayName("Ngày Sinh")]
        [Required(ErrorMessage = "Bạn phải nhập ngày sinh")]
        public Nullable<System.DateTime> ngaysinh { get; set; }
        [DisplayName("Địa Chỉ")]
        [Required(ErrorMessage = "Bạn phải nhập địa chỉ")]
        public string diachi { get; set; }
        [DisplayName("Số Điện Thoại")]
        [Required(ErrorMessage = "Bạn phải nhập số điện thoại")]
        [MaxLength(10)]
        public string sodienthoai { get; set; }
        [DisplayName("Email")]
        [Required(ErrorMessage = "Bạn phải nhập email")]
        public string email { get; set; }
    }
}
