//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace storelaptop.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class sanpham
    {
        [DisplayName("Mã Sản Phẩm")]
        public int masanpham { get; set; }
        [DisplayName("Ảnh")]
        [Required(ErrorMessage = "Bạn phải nhập ảnh")]
        public string anh { get; set; }
        [DisplayName("Tên Sản Phẩm")]
        [Required(ErrorMessage = "Bạn phải nhập tên sản phẩm")]
        public string tensanpham { get; set; }
        [DisplayName("Mô Tả")]
        [Required(ErrorMessage = "Bạn phải nhập mô tả")]
        public string mota { get; set; }
        [DisplayName("Giá")]
        [Required(ErrorMessage = "Bạn phải nhập giá")]
        [Range(1000, 50000000, ErrorMessage = "Nhập giá từ 1000 đến 50000000")]
        public string gia { get; set; }
        public Nullable<int> madanhmucsanpham { get; set; }
    
        public virtual danhmucsanpham danhmucsanpham { get; set; }
    }
}
