//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace storelaptop.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class tintuc
    {
        [DisplayName("Mã Tin Tức")]
        public int matintuc { get; set; }
        [DisplayName("Ảnh")]
        [Required(ErrorMessage = "Bạn phải upload ảnh")]
        public string anh { get; set; }
        [DisplayName("Tên Tin Tức")]
        [Required(ErrorMessage = "Bạn phải nhập tên tin tức")]
        public string tentintuc { get; set; }
        [Required(ErrorMessage = "Bạn phải nhập mô tả")]
        [DisplayName("Mô Tả")]
        public string mota { get; set; }
        [Required(ErrorMessage = "Bạn phải nhập chi tiết")]
        [DisplayName("Chi Tiết")]
        public string chitiet { get; set; }
        public Nullable<int> madanhmuctintuc { get; set; }
    
        public virtual danhmuctintuc danhmuctintuc { get; set; }
    }
}
