//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace storelaptop.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class user_table
    {
        [DisplayName("ID")]
        public int id { get; set; }
        [DisplayName("Tên Tài Khoản")]
        [Required(ErrorMessage = "Bạn phải nhập username")]
        public string user_name { get; set; }
        [DisplayName("Mật Khẩu")]
        [Required(ErrorMessage = "Bạn phải nhập password")]
        public string pass_word { get; set; }
        [DisplayName("FULLNAME")]
        [Required(ErrorMessage = "Bạn phải nhập fullname")]
        public string full_name { get; set; }
    }
}
